name: 'Retrieve the Production for a Platform.sh project that has a GitHub Integration'
description: 'Retrieves the production URL of the integrated Platform.sh project that is connected to a repository'
inputs:
  platformsh_token:
    description: 'Platform.sh API Token. Needed to trigger the source operation.'
    required: true
  project_id:  # owner of the repo
    description: 'Owner/namespace of the target repository. Default of {github.repository}'
    required: true
  provider:
    description: 'PaaS provider. [platform|upsun]. Default of platform'
    default: platform
outputs:
  production_url:
    description: "URL associated with the production environment on Paas provider"
    value: ${{ steps.get-production-url.outputs.production_url }}

# Things we need to do
# Set up our environmental variables so we can use the github cli tool
# See if the platform.sh cli tool is installed
# if not, install the cli
# Get the envirnoment name for the production environment
# Get the primary URL for the production environment
runs:
  using: "composite"
  steps:
    - name: verify and set provider
      shell: bash
      run: |
        provider="${{ inputs.provider }}"
        if [ "platform" != "${{ inputs.provider }}" ] && [ "upsun" != "${{ inputs.provider }}" ]; then
          echo "::warning::The value you provided for Provider is not valid. Setting to default of platform"
          provider="platform"
        fi
        echo "::debug::Setting PaaS provider to ${provider}."
        echo "PROVIDER=${provider}" >> $GITHUB_ENV

    - name: set provider bin path and environment variable
      shell: bash
      run: | 
        # sigh. if the provider is platform, the bin path is .platformsh. otherwise, it's just upsun
        binPath="${PROVIDER}"
        envVarPrefix="${PROVIDER}"
        if [ "platform" = "${PROVIDER}" ]; then
          binPath="${binPath}sh"
        fi
        # use binPath to generate the environment variable prefix, but we need it in all caps
        envVarPrefix=$(tr '[:lower:]' '[:upper:]' <<< "${binPath}")
        binPath=".${binPath}"
        
        echo "::debug::Setting provider bin path to ${binPath}."       
        echo "PROVIDER_BIN_PATH=${binPath}" >> $GITHUB_ENV
        echo "PROVIDER_ENV_PREFIX=${envVarPrefix}" >> $GITHUB_ENV

    # Set up our environmental variables
    - name: 'Setup Environmental Variables'
      shell: bash
      run: |
        echo "${PROVIDER_ENV_PREFIX}_CLI_TOKEN=${{inputs.platformsh_token}}" >> $GITHUB_ENV

    - name: 'Is Platform CLI Installed?'
      id: 'is-psh-cli-installed'
      shell: bash
      run: |
        if ! command -v "${PROVIDER}" >/dev/null; then
          echo "::debug::${PROVIDER} cli not installed. Installing..."
          curl -fsSL https://raw.githubusercontent.com/platformsh/cli/main/installer.sh | VENDOR="${PROVIDER}" bash
          echo "PATH=${HOME}/${PROVIDER_BIN_PATH}/bin:${PATH}" >> $GITHUB_ENV
        fi

    - name: 'Get Production Environment Name'
      id: 'get-prod-env-name'
      shell: bash
      run: |
        prodEnv=$(${PROVIDER} environment:list -p ${{ inputs.project_id }} --type production --columns ID --no-header --format plain --pipe)

        if [[ -z "${prodEnv}" ]]; then
          echo "::error::Was unable to determine the production environment for project id ${{ inputs.project_id }}"
          exit 1;
        fi

        echo "prod_env_name=${prodEnv}" >> $GITHUB_OUTPUT

    - name: 'Get Production URL'
      id: get-production-url
      shell: bash
      run: |
        prodURL=$(${PROVIDER} url -e ${{ steps.get-prod-env-name.outputs.prod_env_name }} -p ${{ inputs.project_id }} --primary --pipe )

        if [[ -z "${prodURL}" ]]; then
          echo "::error::Was unable to determine the production URL for project id ${{ inputs.project_id }}"
          exit 1;
        fi

        echo "::notice::Production URL is ${prodURL}"
        echo "production_url=${prodURL}" >> $GITHUB_OUTPUT